- hosts: "{{ vm_name }}"
  tasks:
  - name: Instala MariaDB
    yum:
     name: mariadb-server
     state: latest

  - name: Inicia e habilita servico
    service:
      name: mariadb
      state: started
      enabled: yes