- hosts: "tag_Name_{{ vm_name }}"
  tasks:
  - name: Instala MariaDB
    yum:
     name: mariadb-server
     state: latest

  - name: Inicia e habilita servico
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Cria database 'quarkus'
    shell: mysql -u root -e "create database quarkus"
    ignore_errors: yes

  - name: Create quarkus user
    shell: mysql -u root -e "grant all privileges on quarkus.* to quarkus@'localhost' identified by 'quarkus'"
    ignore_errors: yes